var shortid = require('shortid');
var User = require('../models/user');
var RNCryptor = require('jscryptor');
var rand = require("random-key");

exports.init = function(io) {

    function rng() {
        var rn = "";
        rn = rand.generate();
        return rn;
    }

    // token provided from user
    // random_number generated by random_token generator 
    function encrypt(token, random_number) {
        var encrypted = RNCryptor.Encrypt(token, random_number);
        return encrypted;
    }

    // random_number provided from server
    // hash provided from client on iOS application
    function decrypt(hash, random_number) {
        var decrypted = RNCryptor.Decrypt(hash, random_number);
        console.log(decrypted)
    }

    function evaluate(token, decrypted) {
        var success_value = 'false';

        if (token.toString() === decrypted.toString()) {
            success_value = 'True';
        }
        else {
            success_value = 'False';
        }

        return success_value;
    }

    var token = 'taco';
    var random_number = rng();
    console.log(random_number);
    console.log('random_number');

    var encryption = encrypt(token, random_number);

    console.log(encryption);
    console.log('encryption');

    var decryption = "";
    var bool_value = 'false';

    
    io.on('connection', function(socket){
        console.log('a user connected');

        io.sockets.emit('handShake', 'This is working');
        socket.broadcast.emit('handShake', 'Do broadcast instead');
        console.log(clients);

        socket.on('lost connection', function(){
            console.log('user lost connection');
        });

        // note capitalization of both handshake functions!!
        socket.on('handShake', function(){
            console.log('Getting HandShake from iOS');
        });

        socket.on('handshake', function(){
            console.log('Getting Handshake from iOS');
            io.sockets.emit("backFromHandshake", "Some Data");
        });

        socket.on('disconnect', function(){
            console.log('user disconnected');
        });

        socket.on('login', function(data){
            console.log('Getting login attempt from iOS device', data);
        });

        socket.on('init_connect', function(paramaters){

            console.log('connect.js javascript file... nothing should print unless iOS app running and matching socked added')
            console.log('serverSocket');
            console.log(paramaters);
            console.log('Receiving params from iOS');
            //testing
            console.log(user.local.email);

            socket.emit('init_token', token);

        });


        socket.on('authClient', function (data) {
            console.log(data);
            User.byClientToken(data.clientToken, function(err, rou) {
                rou[0].clientAuthToken = data.guid;
                rou[0].save(function(err) {
                    if (err) {
                        console.log(err);
                    }
                });
                console.log(rou);
                socket.emit("tryLogin", {form: "wow"});
            });
        });

        // socket.emit('server_response_init_connect', function(key) {
        //     console.log("successfully sent key to Jordan");
        // });


        // --------------------------------------
        // --------------------------------------
        // --------- Securing Tokens ------------
        // --------------------------------------
        // --------------------------------------

        // instead of passing taco, pass a variable which will be determined with a function call that will generate rn

        socket.on('startLogin', function(string) {
            socket.emit('loginRN', random_number);
        }
        
        socket.on('loginHash', function(hash) {
            decryption = decrypt(hash, random_number);
            bool_value = evaluate(token, decryption);
            socket.emit('loginResult', bool_value) {
        }

        });
    });
}